version: '2.4'
services:
  mpd:
    #build:
    #  context: ./
    image: refreshinglyunconcerned/mpd:debian
    container_name: mpd
    ports:
      - 6600:6600
      - 8000:8000
    volumes:
      - ./music:/var/lib/mpd/music:rw
      - ./playlists:/var/lib/mpd/playlists:rw
      - ./data:/var/lib/mpd/data:rw
      #- ./mpd.conf:/etc/mpd.conf:rw
      ## Time:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    cap_add:
      - SYS_NICE
    restart: unless-stopped
